# Generated by Django 6.0.1 on 2026-01-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Academic year (e.g., 2024)')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Aug-Oct)'), (2, 'Q2 (Nov-Jan)'), (3, 'Q3 (Feb-Apr)'), (4, 'Q4 (May-Jul)')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-year', 'quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('SCIENCE', 'Science'), ('SOCIAL_STUDIES', 'Social Studies'), ('PE', 'Physical Education'), ('ART', 'Art'), ('MUSIC', 'Music')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, help_text='Grade score (0-100)', max_digits=5)),
                ('comments', models.TextField(blank=True, help_text='Teacher comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.quarter')),
            ],
            options={
                'ordering': ['-quarter', 'student_name', 'subject'],
                'unique_together': {('student_name', 'subject', 'quarter')},
            },
        ),
    ]
